-- liquibase formatted sql

--changeset Przemyslaw:1 labels:init,tables
--Cennik
CREATE TABLE price_list
(
    id_price_list BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creation_date DATE NOT NULL,
    start_date    DATE NOT NULL
);

--Przedmiot
CREATE TABLE subject
(
    id_subject   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name VARCHAR(50) UNIQUE NOT NULL
);

-- Role
CREATE TABLE role
(
    id_role   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL
);

-- Uzytkownik
CREATE TABLE website_user
(
--Uzytkownik
    id_user             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(50) UNIQUE  NOT NULL,
    password            VARCHAR(50)         NOT NULL,
--Kierownik
    first_name          VARCHAR(50)         NOT NULL,
    last_name           VARCHAR(50)         NOT NULL,
    gender              CHAR(1)             NOT NULL,
    email               VARCHAR(200) UNIQUE NOT NULL,
    phone               VARCHAR(20)  UNIQUE NOT NULL,
--Nauczyciel
    hourly_rate         MONEY,
--Uczen
    id_level            VARCHAR(50),
    guardian_phone      VARCHAR(20) UNIQUE,
    guardian_email      VARCHAR(200) UNIQUE,
    id_price_list       BIGINT REFERENCES price_list (id_price_list),
    discount_percentage INT,
    is_cash_payment     BOOLEAN,
    issue_invoice       BOOLEAN
);

-- Sale
CREATE TABLE room
(
    id_room     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building    VARCHAR(50) UNIQUE NOT NULL,
    floor       INT                NOT NULL,
    room_number INT                NOT NULL
);

--Zajecia
CREATE TABLE tutoring_class
(
    id_class   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_teacher BIGINT       NOT NULL REFERENCES website_user (id_user),
    id_subject BIGINT       NOT NULL REFERENCES subject (id_subject),
    class_name VARCHAR(300) NOT NULL
);

--Kurs
CREATE TABLE course
(
    id_course        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name      VARCHAR(100) NOT NULL,
    price            MONEY        NOT NULL,
    max_participants INT          NOT NULL
);

--Dni zajete
CREATE TABLE user_busy_days
(
    id_user_busy_day BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_the_week  VARCHAR(20) NOT NULL,
    time_from        TIME(6)     NOT NULL,
    time_to          TIME(6)     NOT NULL
);

--Dostepnosc
CREATE TABLE user_availability
(
    id_user_availability BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user              BIGINT NOT NULL REFERENCES website_user (id_user),
    id_user_busy_day     BIGINT NOT NULL REFERENCES user_busy_days (id_user_busy_day)
);

--Przedmiot cennik
CREATE TABLE subject_price_list
(
    id_subject_price_list BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_level           INT    NOT NULL,
    payment_amount        MONEY  NOT NULL,
    teacher_salary        MONEY  NOT NULL,
    id_price_list         BIGINT NOT NULL REFERENCES price_list (id_price_list),
    id_subject            BIGINT NOT NULL REFERENCES subject (id_subject)
);

--Faktura
CREATE TABLE invoice
(
    invoice_number   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name       VARCHAR(50)  NOT NULL,
    last_name        VARCHAR(50)  NOT NULL,
    company_name     VARCHAR(200),
    nip              VARCHAR(13),
    street           VARCHAR(50)  NOT NULL,
    house_number     VARCHAR(10)  NOT NULL,
    apartment_number VARCHAR(10)  NOT NULL,
    city             VARCHAR(100) NOT NULL,
    postal_code      CHAR(6)      NOT NULL,
    issued_by        BIGINT REFERENCES website_user (id_user)
);

--NauczycielPrzedmiot
CREATE TABLE teacher_subject
(
    id_teacher_subject BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_teacher         BIGINT NOT NULL REFERENCES website_user (id_user),
    id_subject         BIGINT NOT NULL REFERENCES subject (id_subject)
);

--UczenKurs
CREATE TABLE student_course
(
    id_student_course BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_student        BIGINT NOT NULL REFERENCES website_user (id_user),
    id_course         BIGINT NOT NULL REFERENCES course (id_course)
);

--UczenZajecia
CREATE TABLE student_class
(
    id_student_class BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_student       BIGINT NOT NULL REFERENCES website_user (id_user),
    id_class         BIGINT NOT NULL REFERENCES tutoring_class (id_class)
);

--Termin zajec
CREATE TABLE class_schedule
(
    id_class_schedule BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_class          BIGINT       NOT NULL REFERENCES tutoring_class (id_class),
    id_room           BIGINT REFERENCES room (id_room),
    class_date        TIMESTAMP(3) NOT NULL,
    is_online         BOOLEAN      NOT NULL,
    is_completed      BOOLEAN      NOT NULL
);

--Obecnosc na zajeciach
CREATE TABLE attendance
(
    id_attendance     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_class_schedule BIGINT  NOT NULL REFERENCES class_schedule (id_class_schedule),
    id_student        BIGINT  NOT NULL REFERENCES website_user (id_user),
    is_present        BOOLEAN NOT NULL
);

--Naleznosc za zajecia
CREATE TABLE payment_for_classes
(
    id_payment        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_class_schedule BIGINT  NOT NULL REFERENCES class_schedule (id_class_schedule),
    amount            MONEY   NOT NULL,
    is_paid           BOOLEAN NOT NULL
);

--Prosby
CREATE TABLE requests
(
    id_request      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_student      BIGINT NOT NULL REFERENCES website_user (id_user),
    id_subject      BIGINT NOT NULL REFERENCES subject (id_subject),
    request_date    DATE   NOT NULL,
    acceptance_date DATE,
    id_teacher      BIGINT REFERENCES website_user (id_user)
);

--Rejestr zmian w terminach
CREATE TABLE schedule_changes_log
(
    id_change         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_class_schedule BIGINT       NOT NULL REFERENCES class_schedule (id_class_schedule),
    id_user           BIGINT       NOT NULL REFERENCES website_user (id_user),
    reason            VARCHAR(100) NOT NULL,
    explanation       TEXT         NOT NULL
);

-- Rezerwacje sal
CREATE TABLE room_reservations
(
    id_reservation   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_room          BIGINT       NOT NULL REFERENCES room (id_room),
    id_teacher       BIGINT       NOT NULL REFERENCES website_user (id_user),
    reservation_from TIMESTAMP(3) NOT NULL,
    reservation_to   TIMESTAMP(3) NOT NULL
);

--UzytkownikRola
CREATE TABLE user_role
(
    id_user_role BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user      BIGINT NOT NULL REFERENCES website_user (id_user),
    id_role      BIGINT NOT NULL REFERENCES role (id_role)
);