package pl.poszkole.PoSzkole.enums;

public enum Reason {
    TEACHER_UNAVAILABLE,
    STUDENT_REQUEST,
    ROOM_UNAVAILABLE,
    ROOM_CHANGE,
    TECHNICAL_ISSUES,
    HOLIDAY,
    CLASS_REASSIGNMENT,
    CANCELLATION_OF_REMAINING_CLASSES,
    OTHER
}
