spring:
  jackson:
    time-zone: Europe/Warsaw
  datasource:
    url: jdbc:postgresql://localhost:5432/poszkole
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: false
        ddl-auto: none
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml